name: oceanparkflutter
description: Ocean Park cooperative game viewer

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/map/tileset_cueva_2.png
    - assets/sprites/Mushroom Idle.png
    - assets/sprites/Mushroom Left.png
    - assets/sprites/Mushroom Right.png
    - assets/sprites/Door Closed.png
    - assets/sprites/Door Open.png
    - assets/sprites/Leaf Key.png
    - assets/tilemaps/level_000_layer_000.json
    - assets/game_data.json

  fonts:
    - family: Pixel
      fonts:
        - asset: assets/fonts/pixel.ttf
